spring.application.name=labJPA_RelationshipsandInheritance

spring.datasource.url=jdbc:mysql://localhost:3306/labjpa
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

